logging:
  level:
    org:
      springframework:
        security: trace

spring:
  datasource:
    url: jdbc:mysql://springsecurity.cvauee0u67c9.ap-northeast-2.rds.amazonaws.com:3306/bank
    username: admin
    password: springsecurity
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: user
      password: 12345


